version: '3.8'
services:
  weather-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
    command:
      [
        "uvicorn",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "app.main:app",
        "--reload",
      ]
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"
    # command:
    #   mongod --quiet --logpath /dev/null
